# Generated by Django 6.0.5 on 2026-05-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('high', '高'), ('middle', '中'), ('low', '低')], default='middle', max_length=10),
        ),
    ]
